Add Traditional Chinese `zh_tw.json`
Scubakay/autorelog pull request #33
Opened 2024-12-07 02:19 UTC by yichifauzi

Add Traditional Chinese localization support

2024-12-07 16:10 UTC, notlin4 requested changes

2024-12-07 16:10 UTC, notlin4 commented on src/main/resources/assets/autorelog/lang/zh_tw.json
> +  "autorelog.midnightconfig.mode.tooltip": "自動：自動重新連線將在閒置時間超過閒置延遲後自動啟動。 手動：輸入指令 「/autorelog」 來啟動或停用自動重新加入。",
```suggestion
  "autorelog.midnightconfig.mode.tooltip": "自動：自動重新連線將在閒置時間超過閒置延遲後自動啟動。手動：輸入指令「/autorelog」來啟動或停用自動重新加入。",
```

2024-12-07 16:10 UTC, notlin4 commented on src/main/resources/assets/autorelog/lang/zh_tw.json
> +  "autorelog.midnightconfig.maxAttempts.tooltip": "自動重新加入應進行的重新連線嘗試最大次數。設為 0 代表無限次嘗試。(請確保伺服器管理員同意此設定!)",
```suggestion
  "autorelog.midnightconfig.maxAttempts.tooltip": "自動重新加入應進行的重新連線嘗試最大次數。設為 0 代表無限次嘗試。（請確保伺服器管理員同意此設定！）",
```

2024-12-07 16:10 UTC, notlin4 commented on src/main/resources/assets/autorelog/lang/zh_tw.json
> +  "autorelog.midnightconfig.title": "AutoRelog 《自動重新加入》",
```suggestion
  "autorelog.midnightconfig.title": "AutoRelog《自動重新加入》",
```

2024-12-17 04:35 UTC, merged

2024-12-17 15:02 UTC, Scubakay commented
Added in version 0.1.2+1.21.4!